{
"name":""
,"copyright":"(c)"
,"defaultScale":8
,"photoLocationTolerancy":0.1
,"stepsToRedraw":99
,"stepsToShowPhoto":10
,"numOfPhotos":10
,"velocityMetersPerSec":100
,"icon":"mybike.png"
,"trackData":[]
}
