//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Role
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Role()
    {
        this.UserRoles = new HashSet<UserRole>();
    }

    public System.Guid RoleID { get; set; }
    public string RoleName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRole> UserRoles { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.UserLocations = new HashSet<UserLocation>();
        this.UserRoles = new HashSet<UserRole>();
    }

    public System.Guid UserID { get; set; }
    public string UserName { get; set; }
    public string UserPassword { get; set; }
    public string FacebookToken { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserLocation> UserLocations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRole> UserRoles { get; set; }
}

public partial class UserLocation
{
    public System.Guid UserLocationID { get; set; }
    public System.Guid UserID { get; set; }
    public double Lat { get; set; }
    public double Lng { get; set; }
    public System.DateTime Time { get; set; }

    public virtual User User { get; set; }
}

public partial class UserRole
{
    public System.Guid UserRoleID { get; set; }
    public System.Guid UserID { get; set; }
    public System.Guid RoleID { get; set; }

    public virtual Role Role { get; set; }
    public virtual User User { get; set; }
}
