USE [master]
GO
CREATE LOGIN [SeeYourTravel] WITH PASSWORD=N'SeeYourTravel', DEFAULT_DATABASE=[SeeYourTravel], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE DATABASE [SeeYourTravel]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SeeYourTravel', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeeYourTravel.mdf' , SIZE = 4096KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SeeYourTravel_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\SeeYourTravel_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SeeYourTravel] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [SeeYourTravel] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SeeYourTravel] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SeeYourTravel] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SeeYourTravel] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SeeYourTravel] SET ARITHABORT OFF 
GO
ALTER DATABASE [SeeYourTravel] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SeeYourTravel] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SeeYourTravel] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SeeYourTravel] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SeeYourTravel] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SeeYourTravel] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SeeYourTravel] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SeeYourTravel] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SeeYourTravel] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SeeYourTravel] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SeeYourTravel] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SeeYourTravel] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SeeYourTravel] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SeeYourTravel] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SeeYourTravel] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SeeYourTravel] SET  READ_WRITE 
GO
ALTER DATABASE [SeeYourTravel] SET RECOVERY FULL 
GO
ALTER DATABASE [SeeYourTravel] SET  MULTI_USER 
GO
ALTER DATABASE [SeeYourTravel] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SeeYourTravel] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SeeYourTravel] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SeeYourTravel]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SeeYourTravel] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [SeeYourTravel]
GO
CREATE USER [SeeYourTravel] FOR LOGIN [SeeYourTravel] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [SeeYourTravel]
GO
ALTER ROLE [db_owner] ADD MEMBER [SeeYourTravel]
GO

USE [SeeYourTravel]
GO

USE [SeeYourTravel]
GO

USE [SeeYourTravel]
GO

/****** Object:  Table [dbo].[UserLocation]    Script Date: 8/3/2015 12:29:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserLocation](
	[UserLocationID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[Lat] [float] NOT NULL,
	[Lng] [float] NOT NULL,
	[Time] [datetime] NOT NULL,
 CONSTRAINT [PK_UserLocation] PRIMARY KEY CLUSTERED 
(
	[UserLocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserLocation] ADD  CONSTRAINT [DF_UserLocation_UserLocationID]  DEFAULT (newid()) FOR [UserLocationID]
GO

ALTER TABLE [dbo].[UserLocation] ADD  CONSTRAINT [DF_UserLocation_Time]  DEFAULT (getdate()) FOR [Time]
GO

ALTER TABLE [dbo].[UserLocation]  WITH CHECK ADD  CONSTRAINT [FK_UserLocation_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[UserLocation] CHECK CONSTRAINT [FK_UserLocation_User]
GO


USE [SeeYourTravel]
GO

/****** Object:  Table [dbo].[Role]    Script Date: 8/3/2015 12:29:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Role](
	[RoleID] [uniqueidentifier] NOT NULL,
	[RoleName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Role] ADD  CONSTRAINT [DF_Role_RoleID]  DEFAULT (newid()) FOR [RoleID]
GO


USE [SeeYourTravel]
GO

/****** Object:  Table [dbo].[User]    Script Date: 8/3/2015 12:29:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[UserID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_User_UserID]  DEFAULT (newid()),
	[UserName] [nvarchar](100) NOT NULL,
	[UserPassword] [nvarchar](100) NOT NULL,
	[FacebookToken] [nvarchar](50) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


USE [SeeYourTravel]
GO

/****** Object:  Table [dbo].[UserRole]    Script Date: 8/3/2015 12:29:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserRole](
	[UserRoleID] [uniqueidentifier] NOT NULL,
	[UserID] [uniqueidentifier] NOT NULL,
	[RoleID] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[UserRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserRole] ADD  CONSTRAINT [DF_UserRole_UserRoleID]  DEFAULT (newid()) FOR [UserRoleID]
GO

ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Role] FOREIGN KEY([RoleID])
REFERENCES [dbo].[Role] ([RoleID])
GO

ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_Role]
GO

ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([UserID])
GO

ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_User]
GO


